services:
  - type: web
    name: bsmotor
    runtime: node
    plan: free
    region: singapore
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: NODE_VERSION
        value: "20.19.2"
